apiVersion: v1
kind: Service
metadata:
  name: eks-sample-linux-service
  namespace: eks-demo-app-nginx
  labels:
    app: eks-sample-linux-app
spec:
  selector:
    app: eks-sample-linux-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
